### ISSUE TITLE
Docker image helayers-lab can not connect to VS Code

### ISSUE THREAD

**Issue by hallojs** [IBM/helayers#19]
Hi,
I followed the installation guide, but unfortunately, I can't connect to the VS Code welcome page of the helayers-lab image. The helayers-pylab image, on the other hand, works fine for me when I follow the installation guide. Is there a way to debug this situation or a typical mistake I may be making?
Thank you very much!

System:
- Ubuntu 20.04.6 LTS Server
- Docker version 24.0.7, build afdd53b
- x86_64 (2x Intel(R) Xeon(R) Gold 6438Y+)

**Comment by aehud** [comment]
We're checking and get back to you very soon.

**Comment by SaidAltury-ibm** [comment]
Hello @hallojs, I appreciate your message.

It seems that there might be a misunderstanding in running both containers simultaneously. There's an issue in our documentation where we mistakenly advise users to use the same host ports for two different containers. Allow me to provide you with the correct instructions:

For pylab container:
```
docker run -p 9999:8888 -d --rm --name helayers-pylab icr.io/helayers/helayers-pylab-x86_64:latest
```
http://127.0.0.1:9999

For lab container:
```
docker run -p 8888:8888 -d --rm --name helayers-lab icr.io/helayers/helayers-lab-x86_64:latest
```
http://127.0.0.1:8888

This should resolve the issue you encountered. If the issue persists, could you provide the error log or more details about the exact situation? This additional information will help us better understand and address the issue you're facing. Feel free to reach out if you have any further questions or need additional assistance.

**Comment by hallojs** [comment]
Hello @SaidAltury-ibm,

thank you for your reply! Now that I see your Docker commands, I probably pulled the wrong images in my first attempt. I loaded the images without the suffix ``-x86_64``. I must have overlooked the table with the exact names in the documentation.

Now it works, thanks!
